name: 'Hello World'
description: 'Greet someone'
inputs:
  CopyBuildToArtifacts:
    description: 'Copy Build to Artifacts'
    required: false
    default: false
  RestoreBuildFromArtifacts:
    description: 'Restore Build From Artifacts'
    required: false
    default: false 
runs:
  using: "composite"
  steps:
    # This step is needed for finding the Powersehll-Script!
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: CopyBuildToArtifacts
      if: ${{ inputs.CopyBuildToArtifacts == 'true' }}
      run: BuildArtifacts.ps1 -CopyBuildToArtifacts
      shell: pwsh
    - name: RestoreBuildFromArtifacts
      if: ${{ inputs.RestoreBuildFromArtifacts == 'true' }}
      run: BuildArtifacts.ps1 -RestoreBuildFromArtifacts
      shell: pwsh